# Generated by Django 4.0 on 2022-01-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('ordering', 'title')},
        ),
        migrations.AddField(
            model_name='product',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
