# Generated by Django 4.0 on 2022-01-05 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_options_product_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_option', models.CharField(max_length=255)),
                ('option_name', models.CharField(default='senior', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.CreateModel(
            name='ProductSelect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_count', models.IntegerField(default=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='products.product')),
                ('product_select', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_selected', to='products.productoption')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_select',
            field=models.ManyToManyField(blank=True, related_name='product_options', through='products.ProductSelect', to='products.ProductOption'),
        ),
    ]
